### ISSUE TITLE
ALttP Items Still Present In Tracker

### ISSUE THREAD

**Issue by UrzaMTG** [j-imbo/pkmnrb_jim#10]
I was trying to determine why Route 9 and 10 show up as accessible once you have access to Lavender Town, even though Cut and Flash are not accessible. I saw that the access requirement was correctly `"$lavendernoflash,[$canflash]"` so I dug into `canflash`. The final line is the following:

`return ((has("flash") or has("lamp")) and badge)`

Pokemon doesn't have a lamp. A Link to the Past does, and apparently items.json still has definitions for all of those items. My proposed fix is to remove all of the LttP items from the tracking, and remove all reference to those items from the logic.

**Comment by j-imbo** [comment]
This doesn't break anything, and in fact since the items don't exist will never be flagged as usable. These items exist in the background of the tracker for when the randomizer gets them as key items as an alternative to HMs, which you can see in https://github.com/ArchipelagoMW/Archipelago/blob/main/worlds/pokemon_rb/items.py on lines 17 and 94-97.

As for the actual issue, were they showing as accessible (green) or out of logic (yellow)? If green, steps to replicate would be appreciated.

**Comment by UrzaMTG** [comment]
They were showing as green, if memory serves, but I think I may have been on an older version when I wrote this and I cannot reproduce it now.
